### ISSUE TITLE
gda.html : onClickRemoveCollumn() and onClickRemoveCell() are not implemented

### ISSUE THREAD

**Issue by lc3t35** [zetapush/zetapush-js-tuto#1]
When you look at the example gda.html :
````
<button onclick="onClickRemoveCollumn()">Remove Collumn</button>
<button onclick="onClickRemoveCell()">Remove Cell</button>
````
But onClickRemoveCollumn() and onClickRemoveCell() are not implemented in script.
Also change onClickRemoveCollumn as onClickRemoveColumn (one l ;)

**Comment by mikaelmorvan** [comment]
button removed
